service: frcTeamUpdateSlackNotifier

provider:
  name: aws
  runtime: nodejs8.10
  stage: prod
  region: us-east-1
  role: arn:aws:iam::XXXXXXXXXXXX:role/teamUpdateSlackNotifierRole # <--hard coded account wth

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /hello
          method: get
  goodbye:
    handler: handler.goodbye
    events:
      - http:
          path: /goodbye
          method: get  

resources:
  Resources:
    myDefaultRole:
      Type: AWS::IAM::Role
      Properties:
        Path: /
        RoleName: teamUpdateSlackNotifierRole 
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        ManagedPolicyArns:
          - arn:aws:iam::aws:policy/AWSLambdaExecute
          - arn:aws:iam::aws:policy/SecretsManagerReadWrite
